"""
indicators.py
Contains functions to calculate technical indicators or features natively.
"""

import pandas as pd
import numpy as np

def add_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply technical indicators to the DataFrame using native pandas logic.
    This eliminates the need for any external libraries like pandas-ta.
    """
    if df.empty:
        print("⚠️ Empty DataFrame provided.")
        return df
        
    print(f"📊 Initial DataFrame shape: {df.shape}")
    old_columns = set(df.columns)
    
    # 1. Simple Moving Averages (SMA)
    df['SMA_20'] = df['close'].rolling(window=20).mean()
    df['SMA_50'] = df['close'].rolling(window=50).mean()
    
    # 2. Exponential Moving Averages (EMA)
    df['EMA_12'] = df['close'].ewm(span=12, adjust=False).mean()
    df['EMA_26'] = df['close'].ewm(span=26, adjust=False).mean()
    
    # 3. MACD
    df['MACD_12_26_9'] = df['EMA_12'] - df['EMA_26']
    df['MACDs_12_26_9'] = df['MACD_12_26_9'].ewm(span=9, adjust=False).mean()
    df['MACDh_12_26_9'] = df['MACD_12_26_9'] - df['MACDs_12_26_9']
    
    # 4. RSI (14-period Wilder's Smoothing)
    delta = df['close'].diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    
    avg_gain = gain.ewm(alpha=1/14, min_periods=14, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/14, min_periods=14, adjust=False).mean()
    
    rs = avg_gain / avg_loss
    df['RSI_14'] = 100 - (100 / (1 + rs))
    df['RSI_14'] = df['RSI_14'].fillna(0)
    
    # 5. Bollinger Bands (20-period, 2 std dev)
    std_20 = df['close'].rolling(window=20).std()
    df['BBU_20_2.0'] = df['SMA_20'] + (2 * std_20)
    df['BBL_20_2.0'] = df['SMA_20'] - (2 * std_20)
    
    # 6. Volume SMA
    df['Volume_SMA_20'] = df['volume'].rolling(window=20).mean()
    
    # Drop rows with NaNs generated by rolling lookbacks
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)
    
    print(f"📉 DataFrame shape after calculating indicators: {df.shape}")
    new_columns = set(df.columns) - old_columns
    print(f"✨ Newly appended columns: {sorted(list(new_columns))}")
    
    return df

def add_indicators_1h(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply technical indicators optimized for 1-hour timeframe using `ta` library.
    (Note: pandas-ta is incompatible with Python 3.10 on PyPI currently).
    """
    if df.empty:
        print("⚠️ Empty DataFrame provided.")
        return df
        
    try:
        import ta
        from ta.trend import SMAIndicator, EMAIndicator, MACD
        from ta.momentum import RSIIndicator, StochasticOscillator
        from ta.volatility import BollingerBands, AverageTrueRange
    except ImportError:
        print("⚠️ `ta` library is not installed. Please run `pip install ta`")
        return df
        
    df = df.copy()
    
    # 1. SMAs
    df['SMA_20'] = SMAIndicator(close=df['close'], window=20).sma_indicator()
    df['SMA_50'] = SMAIndicator(close=df['close'], window=50).sma_indicator()
    
    # 2. EMAs
    df['EMA_9'] = EMAIndicator(close=df['close'], window=9).ema_indicator()
    df['EMA_21'] = EMAIndicator(close=df['close'], window=21).ema_indicator()
    
    # 3. RSIs
    df['RSI_14'] = RSIIndicator(close=df['close'], window=14).rsi()
    df['RSI_7'] = RSIIndicator(close=df['close'], window=7).rsi()
    
    # 4. MACD
    macd_inst = MACD(close=df['close'], window_slow=26, window_fast=12, window_sign=9)
    df['MACD_12_26_9'] = macd_inst.macd()
    df['MACDh_12_26_9'] = macd_inst.macd_diff()
    df['MACDs_12_26_9'] = macd_inst.macd_signal()
        
    # 5. Bollinger Bands
    bbands_inst = BollingerBands(close=df['close'], window=20, window_dev=2)
    df['BBL_20_2.0'] = bbands_inst.bollinger_lband()
    df['BBU_20_2.0'] = bbands_inst.bollinger_hband()
    df['BBM_20_2.0'] = bbands_inst.bollinger_mavg()
        
    # 6. ATR
    atr_inst = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=14)
    df['ATR_14'] = atr_inst.average_true_range()
    
    # 7. Volume SMA & Ratio
    df['Volume_SMA_20'] = SMAIndicator(close=df['volume'], window=20).sma_indicator()
    df['Volume_ratio'] = df['volume'] / df['Volume_SMA_20']
    
    # 8. Stochastic Oscillator
    stoch_inst = StochasticOscillator(high=df['high'], low=df['low'], close=df['close'], window=14, smooth_window=3)
    df['STOCHk_14'] = stoch_inst.stoch()
    df['STOCHd_14_3'] = stoch_inst.stoch_signal()
        
    # Drop NaN rows after calculation
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)
    
    print(f"Indicators added. Columns: {len(df.columns)}. Rows remaining: {len(df)}")
    
    return df


if __name__ == "__main__":
    import os
    script_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    test_file = os.path.join(script_dir, "data", "BTC_USDT_1d.csv")
    
    if os.path.exists(test_file):
        test_df = pd.read_csv(test_file)
        test_df = add_indicators(test_df)
        print("\n📈 First 3 rows of enriched data:")
        print(test_df[['timestamp', 'close', 'SMA_20', 'MACDh_12_26_9', 'RSI_14']].head(3))
    else:
        print("⚠️ Test file not found. Please run fetcher.py first!")
